# permissions for end users to view keepsakes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keepsake-viewer-role
rules:
- apiGroups:
  - keepsake.example.com
  resources:
  - keepsakes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keepsake.example.com
  resources:
  - keepsakes/status
  verbs:
  - get
